### PR TITLE
Make it build & fix a typo

### PR DESCRIPTION
**Pull request by ghost**
Fixed a typo in the readme ("configue" -> "configure"), and made it so that the unakite part of the program builds. It's a bit of an incomplete implementation, with added arguments of the kernel type, but it's better than it not building, and should be easily buildable upon. It's also been tested as being able to install a system.

### CODE REVIEW

**Comment by axtloss** [comment]
what exactly is the kernel argument for?

**Comment by ghost** [comment]
The kernel argument is needed as unakite calls a function which requires an argument of "kernel" for the kernel type (base::install_base_packages).

**Comment by axtloss** [comment]
unakite shouldn't give a choice about what kernel to install in it. I was meaning to make it use `linux`

**Comment by ghost** [comment]
I'll edit my fork to reflect that.

**Comment by axtloss** [comment]
Alright, once that's fixed I'll merge this pr

**Pull request merged**
