### PR TITLE
Enable pipewire for desktops

### PR DESCRIPTION
**Pull request by axtloss**
Automatically installs pipewire, pipewire-pulse, pipewire-jack and pipewire-alsa for every desktop.

### CODE REVIEW

**Comment by axtloss** [comment]
This last commit wasn't an actual merge, I just resolved the conflicts in the web editor

**Review by mchalunderscore — APPROVED** [review]

**Comment by mchalunderscore** [comment]
There's issues with rebasing it seems, I'll sort it out when I get home

**Comment by Trivernis** [comment]
Why are we installing the jack and alsa wrappers too?

**Comment by axtloss** [comment]
in my experience alsa is something that was often needed for sound to properly work.
jack is mostly just a nice to have thing, since often people also use qjackctl for the graph feature in pipewire, which requires pipewire-jack

**Pull request merged**
